version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: ubergo-admin
    restart: unless-stopped
    environment:
      - NODE_ENV=production

