version: '3.8'

services:
  # PostgreSQL Database ds
  postgres:
    image: postgres:17-alpine
    container_name: ubexgo-postgres-dev
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_EXTERNAL:-5433}:5432"
    volumes:
      - ../../tmp/database/postgres_data_dev:/var/lib/postgresql/data
    networks:
      - ubexgo-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API Service (Development mode with hot reload)
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile.dev
    container_name: ubexgo-api-dev
    restart: unless-stopped
    ports:
      - "${API_PORT_EXTERNAL:-4001}:${API_PORT:-4000}"
    env_file:
      - ./.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${API_PORT:-4000}
      API_PORT: ${API_PORT:-4000}
      API_PREFIX: ${API_PREFIX:-/api}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT:-postgres}
      DB_SSL: ${DB_SSL:-false}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7d}
      # OTP Configuration
      OTP_CODE_LENGTH: ${OTP_CODE_LENGTH:-6}
      OTP_EXPIRY_MINUTES: ${OTP_EXPIRY_MINUTES:-5}
      OTP_MAX_ATTEMPTS: ${OTP_MAX_ATTEMPTS:-5}
      # Eskiz SMS Configuration
      ESKIZ_EMAIL: ${ESKIZ_EMAIL}
      ESKIZ_PASSWORD: ${ESKIZ_PASSWORD}
      ESKIZ_TOKEN: ${ESKIZ_TOKEN}
      ESKIZ_API_URL: ${ESKIZ_API_URL:-https://notify.eskiz.uz/api}
      # IVR Configuration
      IVR_API_URL: ${IVR_API_URL}
      IVR_API_KEY: ${IVR_API_KEY}
      # Google SSO
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # Apple SSO
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_KEY_ID: ${APPLE_KEY_ID}
      APPLE_PRIVATE_KEY: ${APPLE_PRIVATE_KEY}
      # CORS
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      CORS_CREDENTIALS: ${CORS_CREDENTIALS:-true}
      # Other
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-5242880}
      UPLOAD_PATH: ${UPLOAD_PATH:-./uploads}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_FILE_PATH: ${LOG_FILE_PATH:-./logs}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ubexgo-network-dev
    volumes:
      - ../../apps/api/src:/app/src:delegated
      - ../../apps/api/package.json:/app/package.json:delegated
      - ../../apps/api/tsconfig.json:/app/tsconfig.json:delegated
      - api_node_modules:/app/node_modules

  # Admin Web App (Development mode with hot reload)
  admin:
    build:
      context: ../../apps/admin
      dockerfile: Dockerfile.dev
    container_name: ubexgo-admin-dev
    restart: unless-stopped
    ports:
      - "${ADMIN_PORT_EXTERNAL:-3001}:5173"
    env_file:
      - ./.env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      VITE_API_URL: ${VITE_API_URL:-http://localhost:4001}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:4001/api}
      VITE_APP_NAME: ${VITE_APP_NAME:-UberGo Admin}
      VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
    depends_on:
      - api
    networks:
      - ubexgo-network-dev
    volumes:
      - ../../apps/admin/src:/app/src:delegated
      - ../../apps/admin/public:/app/public:delegated
      - ../../apps/admin/index.html:/app/index.html:delegated
      - ../../apps/admin/vite.config.ts:/app/vite.config.ts:delegated
      - ../../apps/admin/package.json:/app/package.json:delegated
      - admin_node_modules:/app/node_modules

networks:
  ubexgo-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
    driver: local
  api_node_modules:
    driver: local
  admin_node_modules:
    driver: local

