/**
 * Google Sign-In Configuration
 * 
 * IMPORTANT: Before using Google Sign-In, you must:
 * 1. Add SHA-1 fingerprint to Firebase Console
 * 2. Enable Google Sign-In in Firebase Authentication
 * 3. Download updated google-services.json
 * 4. Add your OAuth client IDs below or in environment variables
 * 
 * See GOOGLE_SIGNIN_FIX.md for detailed setup instructions
 */

export const GOOGLE_CONFIG = {
  /**
   * Web Client ID - Required for both expo-auth-session and native sign-in
   * Get this from Firebase Console → Project Settings → Your Android App
   * Or from Google Cloud Console → APIs & Services → Credentials
   * 
   * Format: xxx-xxx.apps.googleusercontent.com
   */
  webClientId: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || 
    '975847085157-fkftohg6fjs1349u8julpu8glncangpk.apps.googleusercontent.com',

  /**
   * Android Client ID (Optional - automatically generated by Firebase)
   * Only needed if using native Google Sign-In flow
   * This is usually generated automatically when you add SHA-1 fingerprint
   */
  androidClientId: process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID || '',

  /**
   * iOS Client ID (Optional - for iOS builds)
   * Get this from Firebase Console when you add an iOS app
   */
  iosClientId: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID || '',

  /**
   * OAuth Scopes
   * These permissions will be requested from the user
   */
  scopes: ['profile', 'email'],

  /**
   * Configuration status
   * Check if all required credentials are set up
   */
  isConfigured: () => {
    const webClientId = process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || 
      '975847085157-fkftohg6fjs1349u8julpu8glncangpk.apps.googleusercontent.com';
    
    // Web Client ID must not be empty and should be a valid format
    return !!webClientId && webClientId.includes('.apps.googleusercontent.com');
  },

  /**
   * Get configuration errors
   * Returns an array of missing configuration items
   */
  getConfigErrors: (): string[] => {
    const errors: string[] = [];
    
    const webClientId = process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || 
      '975847085157-fkftohg6fjs1349u8julpu8glncangpk.apps.googleusercontent.com';
    
    if (!webClientId) {
      errors.push('Web Client ID is missing');
    } else if (!webClientId.includes('.apps.googleusercontent.com')) {
      errors.push('Web Client ID format is invalid');
    }
    
    return errors;
  },
};

/**
 * Helper function to check if Google Sign-In is properly configured
 * Use this to show helpful error messages to developers
 */
export const validateGoogleConfig = (): { valid: boolean; errors: string[] } => {
  const errors = GOOGLE_CONFIG.getConfigErrors();
  
  if (errors.length > 0) {
    console.warn('⚠️ Google Sign-In Configuration Issues:');
    errors.forEach(error => console.warn(`  - ${error}`));
    console.warn('\n📖 See apps/user-app/GOOGLE_SIGNIN_FIX.md for setup instructions\n');
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
};

export default GOOGLE_CONFIG;

